version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      # Primary container where all steps run
      - image: elderhq/java-circle-image:20170502-1
      # Secondary container with a test eventstore instance
      - image: eventstore/eventstore:release-4.0.3
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Building and running unit tests
          command: . infra/run-tests.sh
      - run:
          name: (Maybe) Running Sonar in preview mode
          command: |
            if [ -n "$CI_PULL_REQUEST" ]; then
              echo "Running Sonar in preview mode for PR $CI_PULL_REQUEST"
              . infra/runsonar-preview.sh
            else
              echo "Not relevant, skipping step"
            fi
      - run:
          name: (Maybe) publishing to maven central or internal nexus
          command: |
            if [[ "${CIRCLE_TAG}" =~ v[0-9]+(\.[0-9]+)* ]]; then
              echo "Publishing to maven central (tag is $CIRCLE_TAG)"
              . infra/publish-artifacts-central.sh
            elif [ -n "${CIRCLE_TAG}" ]; then
              echo "Publishing to internal maven (tag is $CIRCLE_TAG)"
              . infra/publish-artifacts-internal.sh
            else
              echo "Not relevant, skipping step"
            fi
      - run:
          name: (Maybe) Running Sonar in full analysis mode
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Running Sonar full analysis mode"
              . infra/runsonar-full.sh
            else
              echo "Not relevant, skipping step"
            fi
deployment:
  fake_deploy_for_circle_ci_2:
    tag: /.*/
    commands:
      - echo "Placeholder NOOP for tags"
