version: 2
jobs:
  build:
    working_directory: /root/project
    docker:
      - image: circleci/openjdk:9.0-jdk-node-browsers
    steps:
      - checkout
      - run:
          name: Building and running unit tests
          command: . infra/run-tests.sh
      - run:
          name: (Maybe) Publishing official artifacts to Maven Central
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Publishing to maven central"
              . infra/publish-artifacts-central.sh
            else
              echo "Not relevant, skipping step"
            fi
      - run:
          name: (Maybe) Publishing Maven artifacts to Elder Nexus
          command: |
            if [ -n "${CIRCLE_TAG}" ]; then
              echo "Publishing Maven artifacts to Nexus"
              . infra/publish-artifacts-internal.sh
            else
              echo "Not relevant, skipping step"
            fi
      - run:
          name: (Maybe) Running Sonar in preview mode
          command: |
            if [ -n "$CI_PULL_REQUEST" ]; then
              . infra/runsonar-preview.sh
            else
              echo "Not relevant, skipping step"
            fi
      - run:
          name: (Maybe) Running Sonar in full analysis mode
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Running Sonar full analysis mode"
              . infra/runsonar-full.sh
            else
              echo "Not relevant, skipping step"
            fi
deployment:
  fake_deploy_for_circle_ci_2:
    tag: /.*/
    commands:
      - echo "Placeholder NOOP for tags"
