version: 2.1
jobs:
  build-it-all:
    working_directory: /root/project
    docker:
      # Primary container where all steps run
      - image: elderhq/java-circle-image:20170502-1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Building (only)
          command: . infra/run-tests.sh
      - run:
          name: (Maybe) publishing to maven central or internal nexus
          command: |
            if [[ "${CIRCLE_TAG}" =~ v[0-9]+(\.[0-9]+)* ]]; then
              echo "Publishing to maven central (tag is $CIRCLE_TAG)"
              . infra/publish-artifacts-central.sh
            elif [ -n "${CIRCLE_TAG}" ]; then
              echo "Publishing to internal maven (tag is $CIRCLE_TAG)"
              . infra/publish-artifacts-internal.sh
            else
              echo "Not relevant, skipping step"
            fi
workflows:
  build-it-all:
    jobs:
      - build-it-all:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
